### ISSUE TITLE
Please add a FLOSS license

### ISSUE THREAD

**Issue by andreicristianpetcu** [benbasson/newtabhomepage#14]
Hi, 

This addon is under copyright (that's what happens when you do not put a license), it appears in addons.mozilla.org as having "Custom License". I use only free and open source software, and there are many like me.

Please pick a license for your work to make it clear that the source code is available.

Thank you,
Andrei

**Comment by benbasson** [comment]
This add-on is, and has always been licensed under the MPL v1.1, as you can see from the LICENSE file in this repo. 

For whatever reason the MPL v1.1 isn't available on the add-ons site as an option. I don't care enough (or at all, in fact) to find out what the differences are between MPL v1.1 and v2, so rather than update the licence I'll just paste it verbatim into the add-ons site and be done with it.

**Comment by benbasson** [comment]
Licence updated on the add-on website. It still shows as "Custom License", but this is as much effort as I'm going to put in. Open source licences are probably about as far down as it's possible to get on the list of things that I care about.
