### ISSUE TITLE
Content page should receive focus, or URL should be selected, by user preference

### ISSUE THREAD

**Issue by benbasson** [benbasson/newtabhomepage#23]
When opening a tab, the homepage is loaded, but the cursor is placed in the URL/location bar instead of giving focus to the page that was loaded. E.g. if you have google.com as your homepage and press "Home", the cursor goes in the Google search field. If you open a new tab, it goes in the URL bar, at the start, and doesn't even select the URL for easy replacement.

Filed [bug 1411465](https://bugzilla.mozilla.org/show_bug.cgi?id=1411465) to ask for an enhancement to the tab API to allow this to be controlled better.

**Comment by xylo** [comment]
At all effected users: Please vote for benbasson's API enhancement suggestion at [bug 1411465](https://bugzilla.mozilla.org/show_bug.cgi?id=1411465).

**Comment by xylo** [comment]
### Title of the issue

This issue is a bit confusing for me.

First of all, the title of this issue suggests that the page content should be focused after a tab creation.  In my Firefox 57.0 (64-Bit, Kubuntu 17.10) this works already as expected.  So I don't see the problem here.

On the other hand this issue links also to #27 which has been closed in favor of this issue.  And #27 describes actually what I want:  I would like the URL to be focused and selected when a new tab is created or it should be at least possible to select the URL after a tab creation (see #28).  But this is not covered at all by this issue, so I don't know why #27 has been closed.  It probably should be the other way around.

**Comment by benbasson** [comment]
There are only three possible outcomes for where focus should be when a new tab is loaded:

1. The URL bar - and text is not selected.
2. The URL bar - and the whole text is selected.
3. The content page that was loaded - and focus goes wherever that page wants it to, e.g. search box.

Currently the only thing that happens is 1. There is no way to control this at all. After 12 years of maintaining this add-on, I can tell you that there are die-hard supporters of both 2 and 3. 

My preference would be to default to focussing the content page, and let people change that option to focus the URL bar (selecting the text) if they prefer. In that respect, I don't see why there needs to be more than one GitHub tracking issue, although I am happy to change the title of this one.

The fact that you're ever seeing desired behaviour is luck. As far as I'm aware there is no way to deal with this without a resolution to bug 1411465.

I don't know what's going on in #28.

**Comment by xylo** [comment]
Thanks for clarifying the issue description and for updating the title.

**Comment by benbasson** [comment]
Not happening until https://bugzilla.mozilla.org/show_bug.cgi?id=1411465 is resolved. Feel free to create a new issue if that is ever the case.
